#!/usr/bin/python3
# -*- coding: utf-8 -*-

__author__ = 'fi11222'

g_gram_to_pentacode = dict()

# downloaded from https://universaldependencies.org/u/feat/index.html and formated with dnl_morph_attr.py
g_attr_values = [
    ('Abbr', 'abbreviation', [
        ('Yes', 'ABYES', 'it is abbreviation'),
    ]),
    ('Animacy', 'animacy', [
        ('Anim', 'ANANM', 'animate'),
        ('Hum', 'ANHUM', 'human'),
        ('Inan', 'ANINN', 'inanimate'),
        ('Nhum', 'ANNHM', 'non-human'),
    ]),
    ('Aspect', 'aspect', [
        ('Hab', 'ASHAB', 'habitual aspect'),
        ('Imp', 'ASIMP', 'imperfect aspect'),
        ('Iter', 'ASITR', 'iterative / frequentative aspect'),
        ('Perf', 'ASPRF', 'perfect aspect'),
        ('Prog', 'ASPRG', 'progressive aspect'),
        ('Prosp', 'ASPRS', 'prospective aspect'),
    ]),
    ('Case', 'case', [
        ('Abs', 'CSABS', 'absolutive'),
        ('Acc', 'CSACC', 'accusative / oblique'),
        ('Erf', 'CSERG', 'ergative'),
        ('Nom', 'CSNOM', 'nominative / direct'),
        ('Abe', 'CSABE', 'abessive / caritive / privative'),
        ('Ben', 'CSBEN', 'benefactive / destinative'),
        ('Cau', 'CSCAU', 'causative / motivative / purposive'),
        ('Cmp', 'CSCMP', 'comparative'),
        ('Cns', 'CSCNS', 'considerative'),
        ('Com', 'CSCOM', 'comitative / associative'),
        ('Dat', 'CSDAT', 'dative'),
        ('Dis', 'CSDIS', 'distributive'),
        ('Equ', 'CSEQU', 'equative'),
        ('Gen', 'CSGEN', 'genitive'),
        ('Ins', 'CSINS', 'instrumental / instructive'),
        ('Par', 'CSPAR', 'partitive'),
        ('Tem', 'CSTEM', 'temporal'),
        ('Tra', 'CSTRA', 'translative / factive'),
        ('Voc', 'CSVOC', 'vocative'),
        ('Abl', 'CSABL', 'ablative / adelative'),
        ('Add', 'CSADD', 'additive'),
        ('Ade', 'CSADE', 'adessive'),
        ('All', 'CSALL', 'allative / adlative'),
        ('Del', 'CSDEL', 'delative / superelative'),
        ('Ela', 'CSELA', 'elative / inelative'),
        ('Ess', 'CSESS', 'essive / prolative'),
        ('Ill', 'CSILL', 'illative / inlative'),
        ('Ine', 'CSINE', 'inessive'),
        ('Lat', 'CSLAT', 'lative / directional allative'),
        ('Loc', 'CSLOC', 'locative'),
        ('Per', 'CSPER', 'perlative'),
        ('Sbe', 'CSSBE', 'subelative'),
        ('Sbl', 'CSSBL', 'sublative'),
        ('Spl', 'CSSPL', 'superlative'),
        ('Sub', 'CSSUB', 'subessive'),
        ('Sup', 'CSSUP', 'superessive'),
        ('Ter', 'CSTER', 'terminative / terminal allative'),
    ]),
    ('ConjType', 'conjunction type', [
        ('Cmp', 'CTCMP', 'comparing conjunction'),
        ('Oper', 'CTOPR', 'mathematical operator'),
        ('Pred', 'CTPRD', 'subordinating conjunction introducing a secondary predicate'),
    ]),
    ('Clusivity', 'clusivity', [
        ('Ex', 'CLSEX', 'exclusive'),
        ('In', 'CLSIN', 'inclusive'),
    ]),
    ('Definite', 'definiteness or state', [
        ('Com', 'DFCOM', 'complex'),
        ('Cons', 'DFCNS', 'construct state / reduced definiteness'),
        ('Def', 'DFDEF', 'definite'),
        ('Ind', 'DFIND', 'indefinite'),
        ('Spec', 'DFSPC', 'specific indefinite'),
    ]),
    ('Degree', 'degree', [
        ('Abs', 'DGABS', 'absolute superlative'),
        ('Auf', 'DGAUG', 'augmentative'),
        ('Cmp', 'DGCMP', 'comparative, second degree'),
        ('Dim', 'DGDIM', 'diminutive'),
        ('Equ', 'DGEQU', 'equative'),
        ('Pos', 'DGPOS', 'positive, first degree'),
        ('Sup', 'DGSUP', 'superlative, third degree'),
    ]),
    ('Deixis', 'relative location encoded in demonstratives', [
        ('Abv', 'DXABV', 'above the reference point'),
        ('Bel', 'DXBEL', 'below the reference point'),
        ('Even', 'DXEVN', 'at the same level as the reference point'),
        ('Med', 'DXMED', 'medial'),
        ('Nvis', 'DXNVS', 'not visible'),
        ('Prox', 'DXPRX', 'proximate'),
        ('Remt', 'DXRMT', 'remote, distal'),
    ]),
    ('DeixisRef', 'person to which deixis is relative', [
        ('1', 'DRXS1', 'deixis relative to the first person participant (speaker)'),
        ('2', 'DRXS2', 'deixis relative to the second person participant (hearer)'),
    ]),
    ('Evident', 'evidentiality', [
        ('Fh', 'EVDFH', 'firsthand'),
        ('Nfh', 'EVNFH', 'non-firsthand'),
    ]),
    ('ExtPos', 'external part of speech', [
        ('ADJ', 'EPADJ', 'adjective-like expression'),
        ('ADP', 'EPADP', 'adposition-like expression'),
        ('ADV', 'EPADV', 'adverb-like expression'),
        ('AUX', 'EPAUX', 'auxiliary-like expression'),
        ('CCONJ', 'CCONJ', 'coordinating conjunction-like expression'),
        ('DET', 'EPDET', 'determiner-like expression'),
        ('INTJ', 'EINTJ', 'interjection-like expression'),
        ('PRON', 'EPRON', 'pronoun-like expression'),
        ('PROPN', 'PROPN', 'proper noun-like expression'),
        ('SCONJ', 'SCONJ', 'subordinator-like expression'),
    ]),
    ('Foreign', 'is this a foreign word?', [
        ('Yes', 'FRYES', 'it is foreign'),
    ]),
    ('Gender', 'gender', [
        ('Com', 'GNCOM', 'common gender'),
        ('Fem', 'GNFEM', 'feminine gender'),
        ('Masc', 'GMASC', 'masculine gender'),
        ('Neut', 'GNEUT', 'neuter gender'),
    ]),
    ('Mood', 'mood', [
        ('Ben', 'MDBEN', 'benedictive / precative'),
        ('Adm', 'MDADM', 'admirative'),
        ('Cnd', 'MDCND', 'conditional'),
        ('Des', 'MDDES', 'desiderative'),
        ('Imp', 'MDIMP', 'imperative'),
        ('Its', 'MDITS', 'intensive'),
        ('Ind', 'MDIND', 'indicative or realis'),
        ('Int', 'MDINT', 'interrogative'),
        ('Irr', 'MDIRR', 'irrealis'),
        ('Jus', 'MDJUS', 'jussive / injunctive'),
        ('Nec', 'MDNEC', 'necessitative'),
        ('Opt', 'MDOPT', 'optative'),
        ('Pot', 'MDPOT', 'potential'),
        ('Prp', 'MDPRP', 'purposive'),
        ('Qot', 'MDQOT', 'quotative'),
        ('Sub', 'MDSUB', 'subjunctive / conjunctive'),
    ]),
    ('NounClass', 'noun class', [
        ('Bantu1', 'NCBN1', 'singular, persons'),
        ('Bantu2', 'NCBN2', 'plural, persons'),
        ('Bantu3', 'NCBN3', 'singular, plants, thin objects'),
        ('Bantu4', 'NCBN4', 'plural, plants, thin objects'),
        ('Bantu5', 'NCBN5', 'singular, fruits, round objects, paired things'),
        ('Bantu6', 'NCBN6', 'plural, fruits, round objects, paired things'),
        ('Bantu7', 'NCBN7', 'singular, things, diminutives'),
        ('Bantu8', 'NCBN8', 'plural, things, diminutives'),
        ('Bantu9', 'NCBN9', 'singular, animals, things'),
        ('Bantu10', 'NCB10', 'plural, animals, things'),
        ('Bantu11', 'NCB11', 'long thin objects, natural phenomena, abstracts'),
        ('Bantu12', 'NCB12', 'singular, small things, diminutives'),
        ('Bantu13', 'NCB13', 'plural or mass, small amount of mass'),
        ('Bantu14', 'NCB14', 'plural, diminutives'),
        ('Bantu15', 'NCB15', 'verbal nouns, infinitives'),
        ('Bantu16', 'NCB16', 'definite location, close to somethinf'),
        ('Bantu17', 'NCB17', 'indefinite location, direction, movement'),
        ('Bantu18', 'NCB18', 'definite location, inside somethinf'),
        ('Bantu19', 'NCB19', 'little bit of, pejorative plural'),
        ('Bantu20', 'NCB20', 'singular, augmentatives'),
        ('Bantu21', 'NCB21', 'singular, augmentatives, derogatives'),
        ('Bantu22', 'NCB22', 'plural, augmentatives'),
        ('Bantu23', 'NCB23', 'location with place names'),
        ('Wol1', 'NCWL1', 'Wolof noun class 1/k (singular human)'),
        ('Wol2', 'NCWL2', 'Wolof noun class 2/ñ (plural human)'),
        ('Wol3', 'NCWL3', 'Wolof noun class 3/g (singular)'),
        ('Wol4', 'NCWL4', 'Wolof noun class 4/j (singular)'),
        ('Wol5', 'NCWL5', 'Wolof noun class 5/b (singular)'),
        ('Wol6', 'NCWL6', 'Wolof noun class 6/m (singular)'),
        ('Wol7', 'NCWL7', 'Wolof noun class 7/l (singular)'),
        ('Wol8', 'NCWL8', 'Wolof noun class 8/y (plural non-human)'),
        ('Wol9', 'NCWL9', 'Wolof noun class 9/s (singular)'),
        ('Wol10', 'NCW10', 'Wolof noun class 10/w (singular)'),
        ('Wol11', 'NCW11', 'Wolof noun class 11/g (location)'),
        ('Wol12', 'NCW12', 'Wolof noun class 12/n (manner)'),
    ]),
    ('NumType', 'numeral type', [
        (
        'Card', 'NTCRD', 'cardinal number or corresponding interrogative / relative / indefinite / demonstrative word'),
        ('Dist', 'NTDST', 'distributive numeral'),
        ('Frac', 'NTFRC', 'fraction'),
        ('Mult', 'NTMLT',
         'multiplicative numeral or corresponding interrogative / relative / indefinite / demonstrative word'),
        ('Ord', 'NTORD', 'ordinal number or corresponding interrogative / relative / indefinite / demonstrative word'),
        ('Range', 'NTRNG', 'range of values'),
        ('Sets', 'NTSTS', 'number of sets of things; collective numeral'),
    ]),
    ('Number', 'number', [
        ('Coll', 'NMCLL', 'collective / mass / singulare tantum'),
        ('Count', 'NMCNT', 'count plural'),
        ('Dual', 'NDUAL', 'dual number'),
        ('Grpa', 'NMGRP', 'greater paucal number'),
        ('Grpl', 'NMGRL', 'greater plural number'),
        ('Inv', 'NMINV', 'inverse number'),
        ('Pauc', 'NMBPC', 'paucal number'),
        ('Plur', 'NPLUR', 'plural number'),
        ('Ptan', 'NMPTN', 'plurale tantum'),
        ('Sing', 'NSING', 'singular number'),
        ('Tri', 'NMTRI', 'trial number'),
    ]),
    ('Person', 'person', [
        ('0', 'PRSN0', 'zero person'),
        ('1', 'PRSN1', 'first person'),
        ('2', 'PRSN2', 'second person'),
        ('3', 'PRSN3', 'third person'),
        ('4', 'PRSN4', 'fourth person'),
    ]),
    ('Polarity', 'polarity', [
        ('Neg', 'PLNEG', 'negative'),
        ('Pos', 'PLPOS', 'positive, affirmative'),
    ]),
    ('Polite', 'politeness', [
        ('Elev', 'PLELV', 'referent elevatinf'),
        ('Form', 'PLFRM', 'formal register'),
        ('Humb', 'PLHMB', 'speaker humblinf'),
        ('Infm', 'PLINF', 'informal register'),
    ]),
    ('Poss', 'possessive', [
        ('Yes', 'PSYES', 'it is possessive'),
    ]),
    ('PronType', 'pronominal type', [
        ('Art', 'PTART', 'article'),
        ('Dem', 'PTDEM', 'demonstrative pronoun, determiner, numeral or adverb'),
        ('Emp', 'PTEMP', 'emphatic determiner'),
        ('Exc', 'PTEXC', 'exclamative determiner'),
        ('Ind', 'PTIND', 'indefinite pronoun, determiner, numeral or adverb'),
        ('Int', 'PTINT', 'interrogative pronoun, determiner, numeral or adverb'),
        ('Neg', 'PTNEG', 'negative pronoun, determiner or adverb'),
        ('Prs', 'PTPRS', 'personal or possessive personal pronoun or determiner'),
        ('Rcp', 'PTRCP', 'reciprocal pronoun'),
        ('Rel', 'PTREL', 'relative pronoun, determiner, numeral or adverb'),
        ('Tot', 'PTTOT', 'total (collective) pronoun, determiner or adverb'),
    ]),
    ('Reflex', 'reflexive', [
        ('Yes', 'RFYES', 'it is reflexive'),
    ]),
    ('II', 'In Initio', [
        ('iic', 'IICOM', 'in initio compositi'),
        ('iiv', 'IIVRB', 'in initio verbi'),
    ]),
    ('Tense', 'tense', [
        ('Fut', 'TNFUT', 'future tense'),
        ('Imp', 'TNIMP', 'imperfect'),
        ('Past', 'TNPST', 'past tense / preterite / aorist'),
        ('Pqp', 'TNPQP', 'pluperfect'),
        ('Pres', 'TNPRS', 'present / non-past tense / aorist'),
    ]),
    ('Typo', 'is this a misspelled word?', [
        ('Yes', 'TYYES', 'it is typo'),
    ]),
    ('VerbForm', 'form of verb or deverbative', [
        ('Conv', 'VFCNV', 'converb, transgressive, adverbial participle, verbal adverb'),
        ('Fin', 'VFFIN', 'finite verb'),
        ('Gdv', 'VFGDV', 'gerundive'),
        ('Ger', 'VFGER', 'gerund'),
        ('Inf', 'VFINF', 'infinitive'),
        ('Part', 'VFPRT', 'participle, verbal adjective'),
        ('Sup', 'VFSUP', 'supine'),
        ('Cau', 'VFCAU', 'causative'),
        ('Vnoun', 'VFVNN', 'verbal noun, masdar'),
    ]),
    ('VerbConj', 'verb conjugation', [
        ('[1]', 'VBCJ1', 'first conjugation'),
        ('[2]', 'VBCJ2', 'second conjugation'),
        ('[3]', 'VBCJ3', 'third conjugation'),
        ('[4]', 'VBCJ4', '4th conjugation'),
        ('[5]', 'VBCJ5', '5th conjugation'),
        ('[6]', 'VBCJ6', '6th conjugation'),
        ('[7]', 'VBCJ7', '7th conjugation'),
        ('[8]', 'VBCJ8', '8th conjugation'),
        ('[9]', 'VBCJ9', '9th conjugation'),
        ('[10]', 'VCJ10', '10th conjugation'),
    ]),
    ('VerbType', 'verb type', [
        ('Aux', 'VTAUX', 'auxiliary verb'),
        ('Cop', 'VTCOP', 'copula verb'),
        ('Mod', 'VTMOD', 'modal verb'),
        ('Light', 'VTLGH', 'light (support) verb'),
        ('Quasi', 'VTRQS', 'quasi-verb'),
    ]),
    ('Undecided', 'undecided codes', [
        ('act', '__ACT', ''),
        ('agt', '__AGT', ''),
        ('per', '__PER', ''),
        ('tasil', '__TSL', ''),
    ]),
    ('Voice', 'voice', [
        ('Act', 'VCACT', 'active or actor-focus voice'),
        ('Antip', 'VCANT', 'antipassive voice'),
        ('Bfoc', 'VCBFC', 'beneficiary-focus voice'),
        ('Cau', 'VCCAU', 'causative voice'),
        ('Dir', 'VCDIR', 'direct voice'),
        ('Inv', 'VCINV', 'inverse voice'),
        ('Lfoc', 'VCLFC', 'location-focus voice'),
        ('Mid', 'VCMID', 'middle voice'),
        ('Pass', 'VCPSS', 'passive or patient-focus voice'),
        ('Rcp', 'VCRCP', 'reciprocal voice'),
    ])
]

g_nlp_pos_list = [
    ('NPIIC', 'IIC', 'in intio compositi'),
    ('NPIIV', 'IIV', 'in intio verbi'),
    ('NPADJ', 'ADJ', 'adjective'),
    ('NPADP', 'ADP', 'adposition'),
    ('NPADV', 'ADV', 'adverb'),
    ('NPAUX', 'AUX', 'auxiliary'),
    ('NPCNJ', 'CCONJ', 'coordinating conjunction'),
    ('NPDET', 'DET', 'determiner'),
    ('NPIND', 'IND', 'indeclinable'),
    ('NPINT', 'INTJ', 'interjection'),
    ('NPNON', 'NOUN', 'noun'),
    ('NPNUM', 'NUM', 'numeral'),
    ('NPPRT', 'PART', 'particle'),
    ('NPPRN', 'PRON', 'pronoun'),
    ('NPPPN', 'PROPN', 'proper noun'),
    ('NPPCT', 'PUNCT', 'punctuation'),
    ('NPSCJ', 'SCONJ', 'subordinating conjunction'),
    ('NPSYM', 'SYM', 'symbol'),
    ('NPVRB', 'VERB', 'verb'),
    ('NPXXX', 'X', 'other')
]

g_nlp_tag_list = [
    ('NTGSE', '.', 'punctuation mark, sentence closer'),
    ('NTGCM', ',', 'punctuation mark, comma'),
    ('NTLRB', '-LRB-', 'left round bracket'),
    ('NTRRB', '-RRB-', 'right round bracket'),
    ('NTOQM', '``', 'opening quotation mark'),
    ('NTCQM', '""', 'closing quotation mark'),
    ("NTCRM", "''", 'closing quotation mark'),
    ('NTGCL', ':', 'punctuation mark, colon or ellipsis'),
    ('NTDOL', '$', 'symbol, currency'),
    ('NTSRP', '#', 'symbol, number sign'),
    ('NTAFX', 'AFX', 'affix'),
    ('NTGCC', 'CC', 'conjunction, coordinatinf'),
    ('NTGCD', 'CD', 'cardinal number'),
    ('NTGDT', 'DT', 'determiner'),
    ('NTGEX', 'EX', 'existential there'),
    ('NTGFW', 'FW', 'foreign word'),
    ('NTHYP', 'HYPH', 'punctuation mark, hyphen'),
    ('NTGIN', 'IN', 'conjunction, subordinating or preposition'),
    ('NTGJJ', 'JJ', 'adjective (English), other noun-modifier (Chinese)'),
    ('NTJJR', 'JJR', 'adjective, comparative'),
    ('NTJJS', 'JJS', 'adjective, superlative'),
    ('NTGLS', 'LS', 'list item marker'),
    ('NTGMD', 'MD', 'verb, modal auxiliary'),
    ('NTNIL', 'NIL', 'missing taf'),
    ('NTGNN', 'NN', 'noun, singular or mass'),
    ('NTNNP', 'NNP', 'noun, proper singular'),
    ('NTNPP', 'NNPS', 'noun, proper plural'),
    ('NTNNS', 'NNS', 'noun, plural'),
    ('NTPDT', 'PDT', 'predeterminer'),
    ('NTPOS', 'POS', 'possessive endinf'),
    ('NTPRP', 'PRP', 'pronoun, personal'),
    ('NTPR$', 'PRP$', 'pronoun, possessive'),
    ('NTGRB', 'RB', 'adverb'),
    ('NTRBR', 'RBR', 'adverb, comparative'),
    ('NTRBS', 'RBS', 'adverb, superlative'),
    ('NTGRP', 'RP', 'adverb, particle'),
    ('NTGTO', 'TO', 'infinitival “to”'),
    ('NTGUH', 'UH', 'interjection'),
    ('NTGVB', 'VB', 'verb, base form'),
    ('NTVBD', 'VBD', 'verb, past tense'),
    ('NTVBG', 'VBG', 'verb, gerund or present participle'),
    ('NTVBN', 'VBN', 'verb, past participle'),
    ('NTVBP', 'VBP', 'verb, non-3rd person singular present'),
    ('NTVBZ', 'VBZ', 'verb, 3rd person singular present'),
    ('NTWDT', 'WDT', 'wh-determiner'),
    ('NTGWP', 'WP', 'wh-pronoun, personal'),
    ('NTWP$', 'WP$', 'wh-pronoun, possessive'),
    ('NTWRB', 'WRB', 'wh-adverb'),
    ('NTGSP', 'SP', 'space (English), sentence-final particle (Chinese)'),
    ('NTADD', 'ADD', 'email'),
    ('NTNFP', 'NFP', 'superfluous punctuation'),
    ('NTGGW', 'GW', 'additional word in multi-word expression'),
    ('NTGXX', 'XX', 'unknown'),
    ('NTBES', 'BES', 'auxiliary “be”'),
    ('NTHVS', 'HVS', 'forms of “have”'),
    ('NT_SP', '_SP', 'whitespace')
]
# ------------- main() -------------------------------------------------------------------------------------------------
if __name__ == '__main__':
    pass